package guide

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/alehatsman/dex/internal/chunk"
	"github.com/alehatsman/dex/internal/store"
)

// Result reports what a render pass did so the CLI can print a clean
// one-line status (and so --check can decide its exit code).
type Result struct {
	Wrote            bool
	Dirty            bool
	OutputPath       string
	ModuleCount      int
	MaxSummarySeenAt int64
}

// Options drives a single render.
type Options struct {
	// Force re-renders even when the manifest says nothing's dirty.
	Force bool
	// DryRun reports what would happen without writing files.
	DryRun bool
}

// topCentralLimit caps the "Key entry points" list per module. Five is
// enough to surface architectural anchors without burying the section
// in noise; users can chase further via `dex graph callers`.
const topCentralLimit = 5

// Render reads the existing repo_summary + package_summary chunks from
// the store, augments each module with ground-truth graph data
// (exported symbols, top-centrality entry points, imports, used-by),
// formats markdown, and writes <root>/<cfg.Output>.
//
// No LLM calls happen here. The LLM-generated package_summary text is
// kept for narrative flavor; the graph sections are mechanical and
// hallucination-proof.
func Render(ctx context.Context, st *store.Store, root string, cfg Config, opts Options) (*Result, error) {
	res := &Result{OutputPath: filepath.Join(root, cfg.Output)}

	pkgRows, err := st.SummariesByKindWithMeta(ctx, chunk.KindPackageSummary)
	if err != nil {
		return res, fmt.Errorf("load package summaries: %w", err)
	}
	pkgRows = filterFixtureDirs(pkgRows)
	repoRows, err := st.SummariesByKindWithMeta(ctx, chunk.KindRepoSummary)
	if err != nil {
		return res, fmt.Errorf("load repo summary: %w", err)
	}

	res.ModuleCount = len(pkgRows)
	res.MaxSummarySeenAt = maxSeen(pkgRows, repoRows)

	if len(pkgRows) == 0 && len(repoRows) == 0 {
		return res, fmt.Errorf("no summaries in index — run `dex index <path> --summarize` first")
	}

	mf, err := ReadManifest(root)
	if err != nil {
		return res, fmt.Errorf("read manifest: %w", err)
	}

	guideExists := fileExists(res.OutputPath)
	res.Dirty = opts.Force || !guideExists || res.MaxSummarySeenAt > mf.LastSummarySeenAt

	if !res.Dirty {
		return res, nil
	}
	if opts.DryRun {
		return res, nil
	}

	body, err := buildMarkdown(ctx, st, root, repoRows, pkgRows)
	if err != nil {
		return res, fmt.Errorf("build markdown: %w", err)
	}
	if err := os.WriteFile(res.OutputPath, []byte(body), 0o644); err != nil {
		return res, fmt.Errorf("write %s: %w", res.OutputPath, err)
	}
	res.Wrote = true

	mf.LastSummarySeenAt = res.MaxSummarySeenAt
	mf.RenderedAt = time.Now().UnixNano()
	if err := WriteManifest(root, mf); err != nil {
		return res, fmt.Errorf("write manifest: %w", err)
	}
	return res, nil
}

func buildMarkdown(ctx context.Context, st *store.Store, root string, repo, pkgs []store.SummaryRow) (string, error) {
	modPath := readModulePath(root)

	var b strings.Builder
	fmt.Fprintf(&b, "# Project Guide\n\n")
	fmt.Fprintf(&b, "_Generated by dex from %s. Do not edit — re-run `dex guide`._\n\n",
		filepath.Base(root))

	if len(repo) > 0 {
		b.WriteString("## Overview\n\n")
		b.WriteString(strings.TrimSpace(repo[0].Content))
		b.WriteString("\n\n")
	}

	haveOverview := len(repo) > 0
	for _, p := range pkgs {
		// The root package_summary is redundant with the Overview
		// (same content, same scope). Skip it so the guide has one
		// root-level prose section instead of two. If the repo_summary
		// is missing (truncated/never run), fall back to surfacing the
		// root package_summary as the module section.
		if (p.Path == "." || p.Path == "") && haveOverview {
			continue
		}
		label := p.Path
		if label == "." || label == "" {
			label = "(root)"
		}
		fmt.Fprintf(&b, "## Module: %s\n\n", label)
		b.WriteString(strings.TrimSpace(p.Content))
		b.WriteString("\n\n")

		if err := appendGraphSections(ctx, &b, st, p.Path, modPath); err != nil {
			return "", err
		}
	}
	return b.String(), nil
}

// appendGraphSections augments a module section with ground-truth data
// pulled from graph_nodes / graph_edges. Each subsection is rendered
// only if non-empty so non-Go directories (testdata, scripts, docs)
// degrade cleanly to the LLM-generated summary alone.
func appendGraphSections(ctx context.Context, b *strings.Builder, st *store.Store, dir, modPath string) error {
	if dir == "" || dir == "." {
		return nil
	}

	exported, err := st.ExportedSymbolsByDir(ctx, dir)
	if err != nil {
		return fmt.Errorf("exported symbols for %s: %w", dir, err)
	}
	central, err := st.TopCentralByDir(ctx, dir, topCentralLimit, true)
	if err != nil {
		return fmt.Errorf("top central for %s: %w", dir, err)
	}
	// Fallback: tiny packages with no exported high-centrality nodes
	// fall back to internal hot spots. Tagged visibly so an LLM reader
	// doesn't mistake them for the public surface.
	centralIsInternal := false
	if len(central) == 0 {
		central, err = st.TopCentralByDir(ctx, dir, topCentralLimit, false)
		if err != nil {
			return fmt.Errorf("top central (internal) for %s: %w", dir, err)
		}
		centralIsInternal = true
	}
	imports, err := st.ImportsForDir(ctx, dir)
	if err != nil {
		return fmt.Errorf("imports for %s: %w", dir, err)
	}
	usedByPkgs, err := st.UsedByPackages(ctx, dir)
	if err != nil {
		return fmt.Errorf("used-by for %s: %w", dir, err)
	}
	usedBy := trimModulePrefix(usedByPkgs, modPath)

	// Renderer-emitted sections use ### so they're visually distinct
	// from the LLM-generated prose above, which often uses **bold**
	// prefixes that would otherwise blend in.
	if len(exported) > 0 {
		fmt.Fprintf(b, "### Exported API (%d)\n\n", len(exported))
		for _, s := range exported {
			fmt.Fprintf(b, "- `%s` %s — %s:%d\n",
				s.Kind, displayName(s), s.FilePath, s.StartLine)
		}
		b.WriteString("\n")
	}

	if len(central) > 0 {
		heading := "Key entry points"
		if centralIsInternal {
			heading = "Key internal hot spots"
		}
		fmt.Fprintf(b, "### %s (top %d by PageRank)\n\n", heading, len(central))
		for _, s := range central {
			fmt.Fprintf(b, "- `%s` — %s:%d — in-degree %d\n",
				displayName(s), s.FilePath, s.StartLine, s.InDegree)
		}
		b.WriteString("\n")
	}

	if proj, ext := splitImports(imports, modPath); len(proj)+len(ext) > 0 {
		b.WriteString("### Depends on\n\n")
		if len(proj) > 0 {
			fmt.Fprintf(b, "- project: %s\n", strings.Join(proj, ", "))
		}
		if len(ext) > 0 {
			fmt.Fprintf(b, "- external: %s\n", strings.Join(ext, ", "))
		}
		b.WriteString("\n")
	}

	if len(usedBy) > 0 {
		fmt.Fprintf(b, "### Used by\n\n- %s\n\n", strings.Join(usedBy, ", "))
	}
	return nil
}

// displayName picks the most informative identifier for a symbol.
// Methods get QualifiedName ("Store.Search"); plain functions and
// types fall back to Name.
func displayName(s store.GraphSymbol) string {
	if s.Kind == "method" && s.QualifiedName != "" {
		// QualifiedName from go/types tends to read as
		// "pkg/path.Type.Method" — trim everything up to the last
		// "/" then drop the package segment up to the first ".".
		q := s.QualifiedName
		if i := strings.LastIndex(q, "/"); i >= 0 {
			q = q[i+1:]
		}
		if i := strings.Index(q, "."); i >= 0 {
			q = q[i+1:]
		}
		if q != "" {
			return q
		}
	}
	return s.Name
}

// trimModulePrefix strips "<modPath>/" from every entry. If modPath
// is empty, returns the slice unchanged. Used to convert raw Go
// package paths into directory-relative names for display.
func trimModulePrefix(pkgs []string, modPath string) []string {
	if modPath == "" {
		return pkgs
	}
	prefix := modPath + "/"
	out := make([]string, 0, len(pkgs))
	for _, p := range pkgs {
		out = append(out, strings.TrimPrefix(p, prefix))
	}
	return out
}

// splitImports partitions raw imports into project-internal (those
// rooted at modPath) and external (stdlib + third-party). modPath is
// read from go.mod; for non-Go projects it is empty and all imports
// fall into "external".
//
// Project imports are trimmed to drop the module prefix so the guide
// shows "internal/store" rather than the full module path.
func splitImports(imports []string, modPath string) (project, external []string) {
	prefix := ""
	if modPath != "" {
		prefix = modPath + "/"
	}
	for _, imp := range imports {
		if prefix != "" && strings.HasPrefix(imp, prefix) {
			project = append(project, strings.TrimPrefix(imp, prefix))
			continue
		}
		external = append(external, imp)
	}
	sort.Strings(project)
	sort.Strings(external)
	return project, external
}

// readModulePath parses go.mod at root and returns the declared module
// path, or "" if go.mod is missing or unparseable. Reading manually
// avoids pulling in golang.org/x/mod just for a one-line extraction.
func readModulePath(root string) string {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if rest, ok := strings.CutPrefix(line, "module "); ok {
			return strings.TrimSpace(rest)
		}
	}
	return ""
}

// filterFixtureDirs drops package_summary rows whose path lives inside
// a `testdata/` segment. Those are fixtures consumed by tests, not part
// of the project's shipped surface — surfacing them as "modules" in
// LLM_GUIDE inflates the table of contents with noise.
func filterFixtureDirs(rows []store.SummaryRow) []store.SummaryRow {
	out := rows[:0]
	for _, r := range rows {
		if isFixtureDir(r.Path) {
			continue
		}
		out = append(out, r)
	}
	return out
}

// isFixtureDir reports whether p contains a `testdata/` path segment.
// Anchored to segment boundaries so a directory literally named
// `mytestdata` doesn't get caught.
func isFixtureDir(p string) bool {
	if p == "testdata" || strings.HasPrefix(p, "testdata/") {
		return true
	}
	return strings.Contains(p, "/testdata/") || strings.HasSuffix(p, "/testdata")
}

func maxSeen(lists ...[]store.SummaryRow) int64 {
	var m int64
	for _, l := range lists {
		for _, r := range l {
			if r.LastSeenAt > m {
				m = r.LastSeenAt
			}
		}
	}
	return m
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}
