package guide

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/alehatsman/dex/internal/chunk"
	"github.com/alehatsman/dex/internal/store"
)

// Result reports what a render pass did so the CLI can print a clean
// one-line status (and so --check can decide its exit code).
type Result struct {
	Wrote        bool   // true when LLM_GUIDE.txt was (re)written
	Dirty        bool   // true when render-trigger conditions were met
	OutputPath   string // resolved path of LLM_GUIDE.txt
	ModuleCount  int    // package_summary sections rendered
	MaxSummarySeenAt int64 // max(last_seen_at) over rendered summaries
}

// Options drives a single render.
type Options struct {
	// Force re-renders even when the manifest says nothing's dirty.
	// Used by `dex guide --full`.
	Force bool
	// DryRun reports what would happen without writing files.
	// Used by `dex guide --dry-run` and `--check`.
	DryRun bool
}

// Render reads the existing repo_summary + package_summary chunks from
// the store, formats them as markdown, and writes the result to
// <root>/<cfg.Output>. The manifest at <root>/.dex/llm_guide.manifest.json
// is updated on success.
//
// No LLM calls happen here — summaries are already chunks produced by
// the indexer's Pass 5 / Pass 6. This function only formats and writes.
func Render(ctx context.Context, st *store.Store, root string, cfg Config, opts Options) (*Result, error) {
	res := &Result{OutputPath: filepath.Join(root, cfg.Output)}

	pkgRows, err := st.SummariesByKindWithMeta(ctx, chunk.KindPackageSummary)
	if err != nil {
		return res, fmt.Errorf("load package summaries: %w", err)
	}
	repoRows, err := st.SummariesByKindWithMeta(ctx, chunk.KindRepoSummary)
	if err != nil {
		return res, fmt.Errorf("load repo summary: %w", err)
	}

	res.ModuleCount = len(pkgRows)
	res.MaxSummarySeenAt = maxSeen(pkgRows, repoRows)

	if len(pkgRows) == 0 && len(repoRows) == 0 {
		return res, fmt.Errorf("no summaries in index — run `dex index <path> --summarize` first")
	}

	mf, err := ReadManifest(root)
	if err != nil {
		return res, fmt.Errorf("read manifest: %w", err)
	}

	guideExists := fileExists(res.OutputPath)
	res.Dirty = opts.Force || !guideExists || res.MaxSummarySeenAt > mf.LastSummarySeenAt

	if !res.Dirty {
		return res, nil
	}

	if opts.DryRun {
		return res, nil
	}

	body := buildMarkdown(root, repoRows, pkgRows)
	if err := os.WriteFile(res.OutputPath, []byte(body), 0o644); err != nil {
		return res, fmt.Errorf("write %s: %w", res.OutputPath, err)
	}
	res.Wrote = true

	mf.LastSummarySeenAt = res.MaxSummarySeenAt
	mf.RenderedAt = time.Now().UnixNano()
	if err := WriteManifest(root, mf); err != nil {
		return res, fmt.Errorf("write manifest: %w", err)
	}
	return res, nil
}

func buildMarkdown(root string, repo, pkgs []store.SummaryRow) string {
	var b strings.Builder
	b.WriteString("# Project Guide\n\n")
	b.WriteString(fmt.Sprintf("_Generated by dex from %s. Do not edit — re-run `dex guide`._\n\n",
		filepath.Base(root)))

	if len(repo) > 0 {
		b.WriteString("## Overview\n\n")
		b.WriteString(strings.TrimSpace(repo[0].Content))
		b.WriteString("\n\n")
	}

	for _, p := range pkgs {
		mod := p.Path
		if mod == "." || mod == "" {
			mod = "(root)"
		}
		b.WriteString("## Module: ")
		b.WriteString(mod)
		b.WriteString("\n\n")
		b.WriteString(strings.TrimSpace(p.Content))
		b.WriteString("\n\n")
	}
	return b.String()
}

func maxSeen(lists ...[]store.SummaryRow) int64 {
	var m int64
	for _, l := range lists {
		for _, r := range l {
			if r.LastSeenAt > m {
				m = r.LastSeenAt
			}
		}
	}
	return m
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}
